REF_CITY_CHOICES = (
    ("N/A", "N/A"),
    ('Aborlan', 'Aborlan'),
    ('Abra de Ilog', 'Abra de Ilog'),
    ('Abucay', 'Abucay'),
    ('Abulug', 'Abulug'),
    ('Abuyog', 'Abuyog'),
    ('Adams', 'Adams'),
    ('Agdangan', 'Agdangan'),
    ('Aglipay', 'Aglipay'),
    ('Agno', 'Agno'),
    ('Agoncillo', 'Agoncillo'),
    ('Agoo', 'Agoo'),
    ('Aguilar', 'Aguilar'),
    ('Aguinaldo', 'Aguinaldo'),
    ('Agutaya', 'Agutaya'),
    ('Ajuy', 'Ajuy'),
    ('Akbar', 'Akbar'),
    ('Al-Barka', 'Al-Barka'),
    ('Alabat', 'Alabat'),
    ('Alabel', 'Alabel'),
    ('Alamada', 'Alamada'),
    ('Alaminos', 'Alaminos'),
    ('Alangalang', 'Alangalang'),
    ('Albuera', 'Albuera'),
    ('Alburquerque', 'Alburquerque'),
    ('Alcala', 'Alcala'),
    ('Alcantara', 'Alcantara'),
    ('Alcoy', 'Alcoy'),
    ('Alegria', 'Alegria'),
    ('Aleosan', 'Aleosan'),
    ('Alfonso', 'Alfonso'),
    ('Alfonso Castañeda', 'Alfonso Castañeda'),
    ('Alfonso Lista (Potia)', 'Alfonso Lista (Potia)'),
    ('Aliaga', 'Aliaga'),
    ('Alicia', 'Alicia'),
    ('Alilem', 'Alilem'),
    ('Alimodian', 'Alimodian'),
    ('Alitagtag', 'Alitagtag'),
    ('Allacapan', 'Allacapan'),
    ('Allen', 'Allen'),
    ('Almagro', 'Almagro'),
    ('Almeria', 'Almeria'),
    ('Aloguinsan', 'Aloguinsan'),
    ('Aloran', 'Aloran'),
    ('Altavas', 'Altavas'),
    ('Alubijid', 'Alubijid'),
    ('Amadeo', 'Amadeo'),
    ('Amai Manabilang (Bumbaran)', 'Amai Manabilang (Bumbaran)'),
    ('Ambaguio', 'Ambaguio'),
    ('Amlan (Ayuquitan)', 'Amlan (Ayuquitan)'),
    ('Ampatuan', 'Ampatuan'),
    ('Amulung', 'Amulung'),
    ('Anahawan', 'Anahawan'),
    ('Anao', 'Anao'),
    ('Anda', 'Anda'),
    ('Angadanan', 'Angadanan'),
    ('Angat', 'Angat'),
    ('Angeles', 'Angeles'),
    ('Angono', 'Angono'),
    ('Anilao', 'Anilao'),
    ('Anini-y', 'Anini-y'),
    ('Antequera', 'Antequera'),
    ('Antipas', 'Antipas'),
    ('Antipolo', 'Antipolo'),
    ('Apalit', 'Apalit'),
    ('Aparri', 'Aparri'),
    ('Araceli', 'Araceli'),
    ('Arakan', 'Arakan'),
    ('Arayat', 'Arayat'),
    ('Argao', 'Argao'),
    ('Aringay', 'Aringay'),
    ('Aritao', 'Aritao'),
    ('Aroroy', 'Aroroy'),
    ('Arteche', 'Arteche'),
    ('Asingan', 'Asingan'),
    ('Asipulo', 'Asipulo'),
    ('Asturias', 'Asturias'),
    ('Asuncion (Saug)', 'Asuncion (Saug)'),
    ('Atimonan', 'Atimonan'),
    ('Atok', 'Atok'),
    ('Aurora', 'Aurora'),
    ('Ayungon', 'Ayungon'),
    ('Baao', 'Baao'),
    ('Babatngon', 'Babatngon'),
    ('Bacacay', 'Bacacay'),
    ('Bacarra', 'Bacarra'),
    ('Baclayon', 'Baclayon'),
    ('Bacnotan', 'Bacnotan'),
    ('Baco', 'Baco'),
    ('Bacolod', 'Bacolod'),
    ('Bacolod-Kalawi (Bacolod-Grande)', 'Bacolod-Kalawi (Bacolod-Grande)'),
    ('Bacolor', 'Bacolor'),
    ('Bacong', 'Bacong'),
    ('Bacoor', 'Bacoor'),
    ('Bacuag', 'Bacuag'),
    ('Badian', 'Badian'),
    ('Badiangan', 'Badiangan'),
    ('Badoc', 'Badoc'),
    ('Bagabag', 'Bagabag'),
    ('Bagac', 'Bagac'),
    ('Bagamanoc', 'Bagamanoc'),
    ('Baganga', 'Baganga'),
    ('Baggao', 'Baggao'),
    ('Bago', 'Bago'),
    ('Baguio', 'Baguio'),
    ('Bagulin', 'Bagulin'),
    ('Bagumbayan', 'Bagumbayan'),
    ('Bais', 'Bais'),
    ('Bakun', 'Bakun'),
    ('Balabac', 'Balabac'),
    ('Balabagan', 'Balabagan'),
    ('Balagtas (Bigaa)', 'Balagtas (Bigaa)'),
    ('Balamban', 'Balamban'),
    ('Balanga', 'Balanga'),
    ('Balangiga', 'Balangiga'),
    ('Balangkayan', 'Balangkayan'),
    ('Balaoan', 'Balaoan'),
    ('Balasan', 'Balasan'),
    ('Balatan', 'Balatan'),
    ('Balayan', 'Balayan'),
    ('Balbalan', 'Balbalan'),
    ('Baleno', 'Baleno'),
    ('Baler', 'Baler'),
    ('Balete', 'Balete'),
    ('Baliangao', 'Baliangao'),
    ('Baliguian', 'Baliguian'),
    ('Balilihan', 'Balilihan'),
    ('Balindong (Watu)', 'Balindong (Watu)'),
    ('Balingasag', 'Balingasag'),
    ('Balingoan', 'Balingoan'),
    ('Baliuag', 'Baliuag'),
    ('Ballesteros', 'Ballesteros'),
    ('Baloi', 'Baloi'),
    ('Balud', 'Balud'),
    ('Balungao', 'Balungao'),
    ('Bamban', 'Bamban'),
    ('Bambang', 'Bambang'),
    ('Banate', 'Banate'),
    ('Banaue', 'Banaue'),
    ('Banaybanay', 'Banaybanay'),
    ('Banayoyo', 'Banayoyo'),
    ('Banga', 'Banga'),
    ('Bangar', 'Bangar'),
    ('Bangued', 'Bangued'),
    ('Bangui', 'Bangui'),
    ('Banguingui (Tongkil)', 'Banguingui (Tongkil)'),
    ('Bani', 'Bani'),
    ('Banisilan', 'Banisilan'),
    ('Banna (Espiritu)', 'Banna (Espiritu)'),
    ('Bansalan', 'Bansalan'),
    ('Bansud', 'Bansud'),
    ('Bantay', 'Bantay'),
    ('Bantayan', 'Bantayan'),
    ('Banton (Jones)', 'Banton (Jones)'),
    ('Baras', 'Baras'),
    ('Barbaza', 'Barbaza'),
    ('Barcelona', 'Barcelona'),
    ('Barili', 'Barili'),
    ('Barira', 'Barira'),
    ('Barlig', 'Barlig'),
    ('Barobo', 'Barobo'),
    ('Barotac Nuevo', 'Barotac Nuevo'),
    ('Barotac Viejo', 'Barotac Viejo'),
    ('Baroy', 'Baroy'),
    ('Barugo', 'Barugo'),
    ('Basay', 'Basay'),
    ('Basco', 'Basco'),
    ('Basey', 'Basey'),
    ('Basilisa (Rizal)', 'Basilisa (Rizal)'),
    ('Basista', 'Basista'),
    ('Basud', 'Basud'),
    ('Batac', 'Batac'),
    ('Batad', 'Batad'),
    ('Batan', 'Batan'),
    ('Batangas City', 'Batangas City'),
    ('Bataraza', 'Bataraza'),
    ('Bato', 'Bato'),
    ('Batuan', 'Batuan'),
    ('Bauan', 'Bauan'),
    ('Bauang', 'Bauang'),
    ('Bauko', 'Bauko'),
    ('Baungon', 'Baungon'),
    ('Bautista', 'Bautista'),
    ('Bay', 'Bay'),
    ('Bayabas', 'Bayabas'),
    ('Bayambang', 'Bayambang'),
    ('Bayang', 'Bayang'),
    ('Bayawan (Tulong)', 'Bayawan (Tulong)'),
    ('Baybay', 'Baybay'),
    ('Bayog', 'Bayog'),
    ('Bayombong', 'Bayombong'),
    ('Bayugan', 'Bayugan'),
    ('Belison', 'Belison'),
    ('Benito Soliven', 'Benito Soliven'),
    ('Besao', 'Besao'),
    ('Bien Unido', 'Bien Unido'),
    ('Bilar', 'Bilar'),
    ('Biliran', 'Biliran'),
    ('Binalbagan', 'Binalbagan'),
    ('Binalonan', 'Binalonan'),
    ('Biñan', 'Biñan'),
    ('Binangonan', 'Binangonan'),
    ('Bindoy (Payabon)', 'Bindoy (Payabon)'),
    ('Bingawan', 'Bingawan'),
    ('Binidayan', 'Binidayan'),
    ('Binmaley', 'Binmaley'),
    ('Binuangan', 'Binuangan'),
    ('Biri', 'Biri'),
    ('Bislig', 'Bislig'),
    ('Boac', 'Boac'),
    ('Bobon', 'Bobon'),
    ('Bocaue', 'Bocaue'),
    ('Bogo', 'Bogo'),
    ('Bokod', 'Bokod'),
    ('Bolinao', 'Bolinao'),
    ('Boliney', 'Boliney'),
    ('Boljoon', 'Boljoon'),
    ('Bombon', 'Bombon'),
    ('Bongabon', 'Bongabon'),
    ('Bongabong', 'Bongabong'),
    ('Bongao', 'Bongao'),
    ('Bonifacio', 'Bonifacio'),
    ('Bontoc', 'Bontoc'),
    ('Borbon', 'Borbon'),
    ('Borongan', 'Borongan'),
    ('Boston', 'Boston'),
    ('Botolan', 'Botolan'),
    ('Braulio E. Dujali', 'Braulio E. Dujali'),
    ('Brooke's Point', 'Brooke's Point'),
    ('Buadiposo-Buntong', 'Buadiposo-Buntong'),
    ('Bubong', 'Bubong'),
    ('Bucay', 'Bucay'),
    ('Bucloc', 'Bucloc'),
    ('Buenavista', 'Buenavista'),
    ('Bugallon', 'Bugallon'),
    ('Bugasong', 'Bugasong'),
    ('Buguey', 'Buguey'),
    ('Buguias', 'Buguias'),
    ('Buhi', 'Buhi'),
    ('Bula', 'Bula'),
    ('Bulakan', 'Bulakan'),
    ('Bulalacao (San Pedro)', 'Bulalacao (San Pedro)'),
    ('Bulan', 'Bulan'),
    ('Buldon', 'Buldon'),
    ('Buluan', 'Buluan'),
    ('Bulusan', 'Bulusan'),
    ('Bunawan', 'Bunawan'),
    ('Burauen', 'Burauen'),
    ('Burdeos', 'Burdeos'),
    ('Burgos', 'Burgos'),
    ('Buruanga', 'Buruanga'),
    ('Bustos', 'Bustos'),
    ('Busuanga', 'Busuanga'),
    ('Butig', 'Butig'),
    ('Butuan', 'Butuan'),
    ('Buug', 'Buug'),
    ('Caba', 'Caba'),
    ('Cabadbaran', 'Cabadbaran'),
    ('Cabagan', 'Cabagan'),
    ('Cabanatuan', 'Cabanatuan'),
    ('Cabangan', 'Cabangan'),
    ('Cabanglasan', 'Cabanglasan'),
    ('Cabarroguis', 'Cabarroguis'),
    ('Cabatuan', 'Cabatuan'),
    ('Cabiao', 'Cabiao'),
    ('Cabucgayan', 'Cabucgayan'),
    ('Cabugao', 'Cabugao'),
    ('Cabusao', 'Cabusao'),
    ('Cabuyao', 'Cabuyao'),
    ('Cadiz', 'Cadiz'),
    ('Cagayan de Oro', 'Cagayan de Oro'),
    ('Cagayancillo', 'Cagayancillo'),
    ('Cagdianao', 'Cagdianao'),
    ('Cagwait', 'Cagwait'),
    ('Caibiran', 'Caibiran'),
    ('Cainta', 'Cainta'),
    ('Cajidiocan', 'Cajidiocan'),
    ('Calabanga', 'Calabanga'),
    ('Calaca', 'Calaca'),
    ('Calamba', 'Calamba'),
    ('Calanasan', 'Calanasan'),
    ('Calanogas', 'Calanogas'),
    ('Calapan', 'Calapan'),
    ('Calape', 'Calape'),
    ('Calasiao', 'Calasiao'),
    ('Calatagan', 'Calatagan'),
    ('Calatrava', 'Calatrava'),
    ('Calauag', 'Calauag'),
    ('Calauan', 'Calauan'),
    ('Calayan', 'Calayan'),
    ('Calbayog', 'Calbayog'),
    ('Calbiga', 'Calbiga'),
    ('Calinog', 'Calinog'),
    ('Calintaan', 'Calintaan'),
    ('Caloocan', 'Caloocan'),
    ('Calubian', 'Calubian'),
    ('Calumpit', 'Calumpit'),
    ('Caluya', 'Caluya'),
    ('Camalaniugan', 'Camalaniugan'),
    ('Camalig', 'Camalig'),
    ('Camaligan', 'Camaligan'),
    ('Camiling', 'Camiling'),
    ('Can-avid', 'Can-avid'),
    ('Canaman', 'Canaman'),
    ('Candaba', 'Candaba'),
    ('Candelaria', 'Candelaria'),
    ('Candijay', 'Candijay'),
    ('Candon', 'Candon'),
    ('Candoni', 'Candoni'),
    ('Canlaon', 'Canlaon'),
    ('Cantilan', 'Cantilan'),
    ('Caoayan', 'Caoayan'),
    ('Capalonga', 'Capalonga'),
    ('Capas', 'Capas'),
    ('Capoocan', 'Capoocan'),
    ('Capul', 'Capul'),
    ('Caraga', 'Caraga'),
    ('Caramoan', 'Caramoan'),
    ('Caramoran', 'Caramoran'),
    ('Carasi', 'Carasi'),
    ('Carcar', 'Carcar'),
    ('Cardona', 'Cardona'),
    ('Carigara', 'Carigara'),
    ('Carles', 'Carles'),
    ('Carmen', 'Carmen'),
    ('Carmona', 'Carmona'),
    ('Carranglan', 'Carranglan'),
    ('Carrascal', 'Carrascal'),
    ('Casiguran', 'Casiguran'),
    ('Castilla', 'Castilla'),
    ('Castillejos', 'Castillejos'),
    ('Cataingan', 'Cataingan'),
    ('Catanauan', 'Catanauan'),
    ('Catarman', 'Catarman'),
    ('Catbalogan', 'Catbalogan'),
    ('Cateel', 'Cateel'),
    ('Catigbian', 'Catigbian'),
    ('Catmon', 'Catmon'),
    ('Catubig', 'Catubig'),
    ('Cauayan', 'Cauayan'),
    ('Cavinti', 'Cavinti'),
    ('Cavite City', 'Cavite City'),
    ('Cawayan', 'Cawayan'),
    ('Cebu City', 'Cebu City'),
    ('Cervantes', 'Cervantes'),
    ('Clarin', 'Clarin'),
    ('Claver', 'Claver'),
    ('Claveria', 'Claveria'),
    ('Columbio', 'Columbio'),
    ('Compostela', 'Compostela'),
    ('Concepcion', 'Concepcion'),
    ('Conner', 'Conner'),
    ('Consolacion', 'Consolacion'),
    ('Corcuera', 'Corcuera'),
    ('Cordon', 'Cordon'),
    ('Cordova', 'Cordova'),
    ('Corella', 'Corella'),
    ('Coron', 'Coron'),
    ('Cortes', 'Cortes'),
    ('Cotabato City', 'Cotabato City'),
    ('Cuartero', 'Cuartero'),
    ('Cuenca', 'Cuenca'),
    ('Culaba', 'Culaba'),
    ('Culasi', 'Culasi'),
    ('Culion', 'Culion'),
    ('Currimao', 'Currimao'),
    ('Cuyapo', 'Cuyapo'),
    ('Cuyo', 'Cuyo'),
    ('Daanbantayan', 'Daanbantayan'),
    ('Daet', 'Daet'),
    ('Dagami', 'Dagami'),
    ('Dagohoy', 'Dagohoy'),
    ('Daguioman', 'Daguioman'),
    ('Dagupan', 'Dagupan'),
    ('Dalaguete', 'Dalaguete'),
    ('Damulog', 'Damulog'),
    ('Danao', 'Danao'),
    ('Dangcagan', 'Dangcagan'),
    ('Danglas', 'Danglas'),
    ('Dao', 'Dao'),
    ('Dapa', 'Dapa'),
    ('Dapitan', 'Dapitan'),
    ('Daraga (Locsin)', 'Daraga (Locsin)'),
    ('Daram', 'Daram'),
    ('Dasmariñas', 'Dasmariñas'),
    ('Dasol', 'Dasol'),
    ('Datu Abdullah Sangki', 'Datu Abdullah Sangki'),
    ('Datu Anggal Midtimbang', 'Datu Anggal Midtimbang'),
    ('Datu Blah T. Sinsuat', 'Datu Blah T. Sinsuat'),
    ('Datu Hoffer Ampatuan', 'Datu Hoffer Ampatuan'),
    ('Datu Montawal (Pagagawan)', 'Datu Montawal (Pagagawan)'),
    ('Datu Odin Sinsuat (Dinaig)', 'Datu Odin Sinsuat (Dinaig)'),
    ('Datu Paglas', 'Datu Paglas'),
    ('Datu Piang (Dulawan)', 'Datu Piang (Dulawan)'),
    ('Datu Salibo', 'Datu Salibo'),
    ('Datu Saudi-Ampatuan', 'Datu Saudi-Ampatuan'),
    ('Datu Unsay', 'Datu Unsay'),
    ('Dauin', 'Dauin'),
    ('Dauis', 'Dauis'),
    ('Davao City', 'Davao City'),
    ('Del Carmen', 'Del Carmen'),
    ('Del Gallego', 'Del Gallego'),
    ('Delfin Albano (Magsaysay)', 'Delfin Albano (Magsaysay)'),
    ('Diadi', 'Diadi'),
    ('Diffun', 'Diffun'),
    ('Digos', 'Digos'),
    ('Dilasag', 'Dilasag'),
    ('Dimasalang', 'Dimasalang'),
    ('Dimataling', 'Dimataling'),
    ('Dimiao', 'Dimiao'),
    ('Dinagat', 'Dinagat'),
    ('Dinalungan', 'Dinalungan'),
    ('Dinalupihan', 'Dinalupihan'),
    ('Dinapigue', 'Dinapigue'),
    ('Dinas', 'Dinas'),
    ('Dingalan', 'Dingalan'),
    ('Dingle', 'Dingle'),
    ('Dingras', 'Dingras'),
    ('Dipaculao', 'Dipaculao'),
    ('Diplahan', 'Diplahan'),
    ('Dipolog', 'Dipolog'),
    ('Ditsaan-Ramain', 'Ditsaan-Ramain'),
    ('Divilacan', 'Divilacan'),
    ('Dolores', 'Dolores'),
    ('Don Carlos', 'Don Carlos'),
    ('Don Marcelino', 'Don Marcelino'),
    ('Don Victoriano Chiongbian (Don Mariano Marcos)', 'Don Victoriano Chiongbian (Don Mariano Marcos)'),
    ('Doña Remedios Trinidad', 'Doña Remedios Trinidad'),
    ('Donsol', 'Donsol'),
    ('Dueñas', 'Dueñas'),
    ('Duero', 'Duero'),
    ('Dulag', 'Dulag'),
    ('Dumaguete', 'Dumaguete'),
    ('Dumalag', 'Dumalag'),
    ('Dumalinao', 'Dumalinao'),
    ('Dumalneg', 'Dumalneg'),
    ('Dumangas', 'Dumangas'),
    ('Dumanjug', 'Dumanjug'),
    ('Dumaran', 'Dumaran'),
    ('Dumarao', 'Dumarao'),
    ('Dumingag', 'Dumingag'),
    ('Dupax del Norte', 'Dupax del Norte'),
    ('Dupax del Sur', 'Dupax del Sur'),
    ('Echague', 'Echague'),
    ('El Nido (Bacuit)', 'El Nido (Bacuit)'),
    ('El Salvador', 'El Salvador'),
    ('Enrile', 'Enrile'),
    ('Enrique B. Magalona (Saravia)', 'Enrique B. Magalona (Saravia)'),
    ('Enrique Villanueva', 'Enrique Villanueva'),
    ('Escalante', 'Escalante'),
    ('Esperanza', 'Esperanza'),
    ('Estancia', 'Estancia'),
    ('Famy', 'Famy'),
    ('Ferrol', 'Ferrol'),
    ('Flora', 'Flora'),
    ('Floridablanca', 'Floridablanca'),
    ('Gabaldon (Bitulok & Sabani)', 'Gabaldon (Bitulok & Sabani)'),
    ('Gainza', 'Gainza'),
    ('Galimuyod', 'Galimuyod'),
    ('Gamay', 'Gamay'),
    ('Gamu', 'Gamu'),
    ('Ganassi', 'Ganassi'),
    ('Gandara', 'Gandara'),
    ('Gapan', 'Gapan'),
    ('Garchitorena', 'Garchitorena'),
    ('Garcia Hernandez', 'Garcia Hernandez'),
    ('Gasan', 'Gasan'),
    ('Gattaran', 'Gattaran'),
    ('General Emilio Aguinaldo', 'General Emilio Aguinaldo'),
    ('General Luna', 'General Luna'),
    ('General MacArthur', 'General MacArthur'),
    ('General Mamerto Natividad', 'General Mamerto Natividad'),
    ('General Mariano Alvarez', 'General Mariano Alvarez'),
    ('General Nakar', 'General Nakar'),
    ('General Salipada K. Pendatun', 'General Salipada K. Pendatun'),
    ('General Santos (Dadiangas)', 'General Santos (Dadiangas)'),
    ('General Tinio (Papaya)', 'General Tinio (Papaya)'),
    ('General Trias', 'General Trias'),
    ('Gerona', 'Gerona'),
    ('Getafe', 'Getafe'),
    ('Gigaquit', 'Gigaquit'),
    ('Gigmoto', 'Gigmoto'),
    ('Ginatilan', 'Ginatilan'),
    ('Gingoog', 'Gingoog'),
    ('Giporlos', 'Giporlos'),
    ('Gitagum', 'Gitagum'),
    ('Glan', 'Glan'),
    ('Gloria', 'Gloria'),
    ('Goa', 'Goa'),
    ('Godod', 'Godod'),
    ('Gonzaga', 'Gonzaga'),
    ('Governor Generoso', 'Governor Generoso'),
    ('Gregorio del Pilar (Concepcion)', 'Gregorio del Pilar (Concepcion)'),
    ('Guagua', 'Guagua'),
    ('Gubat', 'Gubat'),
    ('Guiguinto', 'Guiguinto'),
    ('Guihulngan', 'Guihulngan'),
    ('Guimba', 'Guimba'),
    ('Guimbal', 'Guimbal'),
    ('Guinayangan', 'Guinayangan'),
    ('Guindulman', 'Guindulman'),
    ('Guindulungan', 'Guindulungan'),
    ('Guinobatan', 'Guinobatan'),
    ('Guinsiliban', 'Guinsiliban'),
    ('Guipos', 'Guipos'),
    ('Guiuan', 'Guiuan'),
    ('Gumaca', 'Gumaca'),
    ('Gutalac', 'Gutalac'),
    ('Hadji Mohammad Ajul', 'Hadji Mohammad Ajul'),
    ('Hadji Muhtamad', 'Hadji Muhtamad'),
    ('Hadji Panglima Tahil (Marunggas)', 'Hadji Panglima Tahil (Marunggas)'),
    ('Hagonoy', 'Hagonoy'),
    ('Hamtic', 'Hamtic'),
    ('Hermosa', 'Hermosa'),
    ('Hernani', 'Hernani'),
    ('Hilongos', 'Hilongos'),
    ('Himamaylan', 'Himamaylan'),
    ('Hinabangan', 'Hinabangan'),
    ('Hinatuan', 'Hinatuan'),
    ('Hindang', 'Hindang'),
    ('Hingyon', 'Hingyon'),
    ('Hinigaran', 'Hinigaran'),
    ('Hinoba-an (Asia)', 'Hinoba-an (Asia)'),
    ('Hinunangan', 'Hinunangan'),
    ('Hinundayan', 'Hinundayan'),
    ('Hungduan', 'Hungduan'),
    ('Iba', 'Iba'),
    ('Ibaan', 'Ibaan'),
    ('Ibajay', 'Ibajay'),
    ('Igbaras', 'Igbaras'),
    ('Iguig', 'Iguig'),
    ('Ilagan', 'Ilagan'),
    ('Iligan', 'Iligan'),
    ('Ilog', 'Ilog'),
    ('Iloilo City', 'Iloilo City'),
    ('Imelda', 'Imelda'),
    ('Impasugong', 'Impasugong'),
    ('Imus', 'Imus'),
    ('Inabanga', 'Inabanga'),
    ('Indanan', 'Indanan'),
    ('Indang', 'Indang'),
    ('Infanta', 'Infanta'),
    ('Initao', 'Initao'),
    ('Inopacan', 'Inopacan'),
    ('Ipil', 'Ipil'),
    ('Iriga', 'Iriga'),
    ('Irosin', 'Irosin'),
    ('Isabel', 'Isabel'),
    ('Isabela', 'Isabela'),
    ('Isabela City', 'Isabela City'),
    ('Isulan', 'Isulan'),
    ('Itbayat', 'Itbayat'),
    ('Itogon', 'Itogon'),
    ('Ivana', 'Ivana'),
    ('Ivisan', 'Ivisan'),
    ('Jabonga', 'Jabonga'),
    ('Jaen', 'Jaen'),
    ('Jagna', 'Jagna'),
    ('Jalajala', 'Jalajala'),
    ('Jamindan', 'Jamindan'),
    ('Janiuay', 'Janiuay'),
    ('Jaro', 'Jaro'),
    ('Jasaan', 'Jasaan'),
    ('Javier (Bugho)', 'Javier (Bugho)'),
    ('Jiabong', 'Jiabong'),
    ('Jimalalud', 'Jimalalud'),
    ('Jimenez', 'Jimenez'),
    ('Jipapad', 'Jipapad'),
    ('Jolo', 'Jolo'),
    ('Jomalig', 'Jomalig'),
    ('Jones', 'Jones'),
    ('Jordan', 'Jordan'),
    ('Jose Abad Santos (Trinidad)', 'Jose Abad Santos (Trinidad)'),
    ('Jose Dalman (Ponot)', 'Jose Dalman (Ponot)'),
    ('Jose Panganiban', 'Jose Panganiban'),
    ('Josefina', 'Josefina'),
    ('Jovellar', 'Jovellar'),
    ('Juban', 'Juban'),
    ('Julita', 'Julita'),
    ('Kabacan', 'Kabacan'),
    ('Kabankalan', 'Kabankalan'),
    ('Kabasalan', 'Kabasalan'),
    ('Kabayan', 'Kabayan'),
    ('Kabugao', 'Kabugao'),
    ('Kabuntalan (Tumbao)', 'Kabuntalan (Tumbao)'),
    ('Kadingilan', 'Kadingilan'),
    ('Kalamansig', 'Kalamansig'),
    ('Kalawit', 'Kalawit'),
    ('Kalayaan', 'Kalayaan'),
    ('Kalibo', 'Kalibo'),
    ('Kalilangan', 'Kalilangan'),
    ('Kalingalan Caluang', 'Kalingalan Caluang'),
    ('Kananga', 'Kananga'),
    ('Kapai', 'Kapai'),
    ('Kapalong', 'Kapalong'),
    ('Kapangan', 'Kapangan'),
    ('Kapatagan', 'Kapatagan'),
    ('Kasibu', 'Kasibu'),
    ('Katipunan', 'Katipunan'),
    ('Kauswagan', 'Kauswagan'),
    ('Kawayan', 'Kawayan'),
    ('Kawit', 'Kawit'),
    ('Kayapa', 'Kayapa'),
    ('Kiamba', 'Kiamba'),
    ('Kiangan', 'Kiangan'),
    ('Kibawe', 'Kibawe'),
    ('Kiblawan', 'Kiblawan'),
    ('Kibungan', 'Kibungan'),
    ('Kidapawan', 'Kidapawan'),
    ('Kinoguitan', 'Kinoguitan'),
    ('Kitaotao', 'Kitaotao'),
    ('Kitcharao', 'Kitcharao'),
    ('Kolambugan', 'Kolambugan'),
    ('Koronadal', 'Koronadal'),
    ('Kumalarang', 'Kumalarang'),
    ('La Carlota', 'La Carlota'),
    ('La Castellana', 'La Castellana'),
    ('La Libertad', 'La Libertad'),
    ('La Paz', 'La Paz'),
    ('La Trinidad', 'La Trinidad'),
    ('Laak (San Vicente)', 'Laak (San Vicente)'),
    ('Labangan', 'Labangan'),
    ('Labason', 'Labason'),
    ('Labo', 'Labo'),
    ('Labrador', 'Labrador'),
    ('Lacub', 'Lacub'),
    ('Lagangilang', 'Lagangilang'),
    ('Lagawe', 'Lagawe'),
    ('Lagayan', 'Lagayan'),
    ('Lagonglong', 'Lagonglong'),
    ('Lagonoy', 'Lagonoy'),
    ('Laguindingan', 'Laguindingan'),
    ('Lake Sebu', 'Lake Sebu'),
    ('Lakewood', 'Lakewood'),
    ('Lal-lo', 'Lal-lo'),
    ('Lala', 'Lala'),
    ('Lambayong (Mariano Marcos)', 'Lambayong (Mariano Marcos)'),
    ('Lambunao', 'Lambunao'),
    ('Lamitan', 'Lamitan'),
    ('Lamut', 'Lamut'),
    ('Langiden', 'Langiden'),
    ('Languyan', 'Languyan'),
    ('Lantapan', 'Lantapan'),
    ('Lantawan', 'Lantawan'),
    ('Lanuza', 'Lanuza'),
    ('Laoac', 'Laoac'),
    ('Laoag', 'Laoag'),
    ('Laoang', 'Laoang'),
    ('Lapinig', 'Lapinig'),
    ('Lapu-Lapu (Opon)', 'Lapu-Lapu (Opon)'),
    ('Lapuyan', 'Lapuyan'),
    ('Larena', 'Larena'),
    ('Las Navas', 'Las Navas'),
    ('Las Nieves', 'Las Nieves'),
    ('Las Piñas', 'Las Piñas'),
    ('Lasam', 'Lasam'),
    ('Laua-an', 'Laua-an'),
    ('Laur', 'Laur'),
    ('Laurel', 'Laurel'),
    ('Lavezares', 'Lavezares'),
    ('Lawaan', 'Lawaan'),
    ('Lazi', 'Lazi'),
    ('Lebak', 'Lebak'),
    ('Leganes', 'Leganes'),
    ('Legazpi', 'Legazpi'),
    ('Lemery', 'Lemery'),
    ('Leon', 'Leon'),
    ('Leon B. Postigo (Bacungan)', 'Leon B. Postigo (Bacungan)'),
    ('Leyte', 'Leyte'),
    ('Lezo', 'Lezo'),
    ('Lian', 'Lian'),
    ('Lianga', 'Lianga'),
    ('Libacao', 'Libacao'),
    ('Libagon', 'Libagon'),
    ('Libertad', 'Libertad'),
    ('Libjo (Albor)', 'Libjo (Albor)'),
    ('Libmanan', 'Libmanan'),
    ('Libon', 'Libon'),
    ('Libona', 'Libona'),
    ('Libungan', 'Libungan'),
    ('Licab', 'Licab'),
    ('Licuan-Baay (Licuan)', 'Licuan-Baay (Licuan)'),
    ('Lidlidda', 'Lidlidda'),
    ('Ligao', 'Ligao'),
    ('Lila', 'Lila'),
    ('Liliw', 'Liliw'),
    ('Liloan', 'Liloan'),
    ('Liloy', 'Liloy'),
    ('Limasawa', 'Limasawa'),
    ('Limay', 'Limay'),
    ('Linamon', 'Linamon'),
    ('Linapacan', 'Linapacan'),
    ('Lingayen', 'Lingayen'),
    ('Lingig', 'Lingig'),
    ('Lipa', 'Lipa'),
    ('Llanera', 'Llanera'),
    ('Llorente', 'Llorente'),
    ('Loay', 'Loay'),
    ('Lobo', 'Lobo'),
    ('Loboc', 'Loboc'),
    ('Looc', 'Looc'),
    ('Loon', 'Loon'),
    ('Lope de Vega', 'Lope de Vega'),
    ('Lopez', 'Lopez'),
    ('Lopez Jaena', 'Lopez Jaena'),
    ('Loreto', 'Loreto'),
    ('Los Baños', 'Los Baños'),
    ('Luba', 'Luba'),
    ('Lubang', 'Lubang'),
    ('Lubao', 'Lubao'),
    ('Lubuagan', 'Lubuagan'),
    ('Lucban', 'Lucban'),
    ('Lucena', 'Lucena'),
    ('Lugait', 'Lugait'),
    ('Lugus', 'Lugus'),
    ('Luisiana', 'Luisiana'),
    ('Lumba-Bayabao (Maguing)', 'Lumba-Bayabao (Maguing)'),
    ('Lumbaca-Unayan', 'Lumbaca-Unayan'),
    ('Lumban', 'Lumban'),
    ('Lumbatan', 'Lumbatan'),
    ('Lumbayanague', 'Lumbayanague'),
    ('Luna', 'Luna'),
    ('Lupao', 'Lupao'),
    ('Lupi', 'Lupi'),
    ('Lupon', 'Lupon'),
    ('Lutayan', 'Lutayan'),
    ('Luuk', 'Luuk'),
    ('M'lang', 'M'lang'),
    ('Maasim', 'Maasim'),
    ('Maasin', 'Maasin'),
    ('Maayon', 'Maayon'),
    ('Mabalacat', 'Mabalacat'),
    ('Mabinay', 'Mabinay'),
    ('Mabini', 'Mabini'),
    ('Mabini (Doña Alicia)', 'Mabini (Doña Alicia)'),
    ('Mabitac', 'Mabitac'),
    ('Mabuhay', 'Mabuhay'),
    ('Macabebe', 'Macabebe'),
    ('Macalelon', 'Macalelon'),
    ('MacArthur', 'MacArthur'),
    ('Maco', 'Maco'),
    ('Maconacon', 'Maconacon'),
    ('Macrohon', 'Macrohon'),
    ('Madalag', 'Madalag'),
    ('Madalum', 'Madalum'),
    ('Madamba', 'Madamba'),
    ('Maddela', 'Maddela'),
    ('Madrid', 'Madrid'),
    ('Madridejos', 'Madridejos'),
    ('Magalang', 'Magalang'),
    ('Magallanes', 'Magallanes'),
    ('Magarao', 'Magarao'),
    ('Magdalena', 'Magdalena'),
    ('Magdiwang', 'Magdiwang'),
    ('Magpet', 'Magpet'),
    ('Magsaysay', 'Magsaysay'),
    ('Magsaysay (Linugos)', 'Magsaysay (Linugos)'),
    ('Magsingal', 'Magsingal'),
    ('Maguing', 'Maguing'),
    ('Mahaplag', 'Mahaplag'),
    ('Mahatao', 'Mahatao'),
    ('Mahayag', 'Mahayag'),
    ('Mahinog', 'Mahinog'),
    ('Maigo', 'Maigo'),
    ('Maimbung', 'Maimbung'),
    ('Mainit', 'Mainit'),
    ('Maitum', 'Maitum'),
    ('Majayjay', 'Majayjay'),
    ('Makati', 'Makati'),
    ('Makato', 'Makato'),
    ('Makilala', 'Makilala'),
    ('Malabang', 'Malabang'),
    ('Malabon', 'Malabon'),
    ('Malabuyoc', 'Malabuyoc'),
    ('Malalag', 'Malalag'),
    ('Malangas', 'Malangas'),
    ('Malapatan', 'Malapatan'),
    ('Malasiqui', 'Malasiqui'),
    ('Malay', 'Malay'),
    ('Malaybalay', 'Malaybalay'),
    ('Malibcong', 'Malibcong'),
    ('Malilipot', 'Malilipot'),
    ('Malimono', 'Malimono'),
    ('Malinao', 'Malinao'),
    ('Malita', 'Malita'),
    ('Malitbog', 'Malitbog'),
    ('Mallig', 'Mallig'),
    ('Malolos', 'Malolos'),
    ('Malungon', 'Malungon'),
    ('Maluso', 'Maluso'),
    ('Malvar', 'Malvar'),
    ('Mamasapano', 'Mamasapano'),
    ('Mambajao', 'Mambajao'),
    ('Mamburao', 'Mamburao'),
    ('Mambusao', 'Mambusao'),
    ('Manabo', 'Manabo'),
    ('Manaoag', 'Manaoag'),
    ('Manapla', 'Manapla'),
    ('Manay', 'Manay'),
    ('Mandaluyong', 'Mandaluyong'),
    ('Mandaon', 'Mandaon'),
    ('Mandaue', 'Mandaue'),
    ('Mangaldan', 'Mangaldan'),
    ('Mangatarem', 'Mangatarem'),
    ('Mangudadatu', 'Mangudadatu'),
    ('Manila', 'Manila'),
    ('Manito', 'Manito'),
    ('Manjuyod', 'Manjuyod'),
    ('Mankayan', 'Mankayan'),
    ('Manolo Fortich', 'Manolo Fortich'),
    ('Mansalay', 'Mansalay'),
    ('Manticao', 'Manticao'),
    ('Manukan', 'Manukan'),
    ('Mapanas', 'Mapanas'),
    ('Mapandan', 'Mapandan'),
    ('Mapun (Cagayan de Tawi-Tawi)', 'Mapun (Cagayan de Tawi-Tawi)'),
    ('Marabut', 'Marabut'),
    ('Maragondon', 'Maragondon'),
    ('Maragusan (San Mariano)', 'Maragusan (San Mariano)'),
    ('Maramag', 'Maramag'),
    ('Marantao', 'Marantao'),
    ('Marawi', 'Marawi'),
    ('Marcos', 'Marcos'),
    ('Margosatubig', 'Margosatubig'),
    ('Maria', 'Maria'),
    ('Maria Aurora', 'Maria Aurora'),
    ('Maribojoc', 'Maribojoc'),
    ('Marihatag', 'Marihatag'),
    ('Marikina', 'Marikina'),
    ('Marilao', 'Marilao'),
    ('Maripipi', 'Maripipi'),
    ('Mariveles', 'Mariveles'),
    ('Marogong', 'Marogong'),
    ('Masantol', 'Masantol'),
    ('Masbate City', 'Masbate City'),
    ('Masinloc', 'Masinloc'),
    ('Masiu', 'Masiu'),
    ('Maslog', 'Maslog'),
    ('Mataasnakahoy', 'Mataasnakahoy'),
    ('Matag-ob', 'Matag-ob'),
    ('Matalam', 'Matalam'),
    ('Matalom', 'Matalom'),
    ('Matanao', 'Matanao'),
    ('Matanog', 'Matanog'),
    ('Mati', 'Mati'),
    ('Matnog', 'Matnog'),
    ('Matuguinao', 'Matuguinao'),
    ('Matungao', 'Matungao'),
    ('Mauban', 'Mauban'),
    ('Mawab', 'Mawab'),
    ('Mayantoc', 'Mayantoc'),
    ('Maydolong', 'Maydolong'),
    ('Mayorga', 'Mayorga'),
    ('Mayoyao', 'Mayoyao'),
    ('Medellin', 'Medellin'),
    ('Medina', 'Medina'),
    ('Mendez (Mendez-Nuñez)', 'Mendez (Mendez-Nuñez)'),
    ('Mercedes', 'Mercedes'),
    ('Merida', 'Merida'),
    ('Mexico', 'Mexico'),
    ('Meycauayan', 'Meycauayan'),
    ('Miagao', 'Miagao'),
    ('Midsalip', 'Midsalip'),
    ('Midsayap', 'Midsayap'),
    ('Milagros', 'Milagros'),
    ('Milaor', 'Milaor'),
    ('Mina', 'Mina'),
    ('Minalabac', 'Minalabac'),
    ('Minalin', 'Minalin'),
    ('Minglanilla', 'Minglanilla'),
    ('Moalboal', 'Moalboal'),
    ('Mobo', 'Mobo'),
    ('Mogpog', 'Mogpog'),
    ('Moises Padilla (Magallon)', 'Moises Padilla (Magallon)'),
    ('Molave', 'Molave'),
    ('Moncada', 'Moncada'),
    ('Mondragon', 'Mondragon'),
    ('Monkayo', 'Monkayo'),
    ('Monreal', 'Monreal'),
    ('Montevista', 'Montevista'),
    ('Morong', 'Morong'),
    ('Motiong', 'Motiong'),
    ('Mulanay', 'Mulanay'),
    ('Mulondo', 'Mulondo'),
    ('Munai', 'Munai'),
    ('Muñoz', 'Muñoz'),
    ('Muntinlupa', 'Muntinlupa'),
    ('Murcia', 'Murcia'),
    ('Mutia', 'Mutia'),
    ('Naawan', 'Naawan'),
    ('Nabas', 'Nabas'),
    ('Nabua', 'Nabua'),
    ('Nabunturan', 'Nabunturan'),
    ('Naga', 'Naga'),
    ('Nagbukel', 'Nagbukel'),
    ('Nagcarlan', 'Nagcarlan'),
    ('Nagtipunan', 'Nagtipunan'),
    ('Naguilian', 'Naguilian'),
    ('Naic', 'Naic'),
    ('Nampicuan', 'Nampicuan'),
    ('Narra', 'Narra'),
    ('Narvacan', 'Narvacan'),
    ('Nasipit', 'Nasipit'),
    ('Nasugbu', 'Nasugbu'),
    ('Natividad', 'Natividad'),
    ('Natonin', 'Natonin'),
    ('Naujan', 'Naujan'),
    ('Naval', 'Naval'),
    ('Navotas', 'Navotas'),
    ('New Bataan', 'New Bataan'),
    ('New Corella', 'New Corella'),
    ('New Lucena', 'New Lucena'),
    ('New Washington', 'New Washington'),
    ('Norala', 'Norala'),
    ('Northern Kabuntalan', 'Northern Kabuntalan'),
    ('Norzagaray', 'Norzagaray'),
    ('Noveleta', 'Noveleta'),
    ('Nueva Era', 'Nueva Era'),
    ('Nueva Valencia', 'Nueva Valencia'),
    ('Numancia', 'Numancia'),
    ('Nunungan', 'Nunungan'),
    ('Oas', 'Oas'),
    ('Obando', 'Obando'),
    ('Ocampo', 'Ocampo'),
    ('Odiongan', 'Odiongan'),
    ('Old Panamao', 'Old Panamao'),
    ('Olongapo', 'Olongapo'),
    ('Olutanga', 'Olutanga'),
    ('Omar', 'Omar'),
    ('Opol', 'Opol'),
    ('Orani', 'Orani'),
    ('Oras', 'Oras'),
    ('Orion', 'Orion'),
    ('Ormoc', 'Ormoc'),
    ('Oroquieta', 'Oroquieta'),
    ('Oslob', 'Oslob'),
    ('Oton', 'Oton'),
    ('Ozamiz', 'Ozamiz'),
    ('Padada', 'Padada'),
    ('Padre Burgos', 'Padre Burgos'),
    ('Padre Garcia', 'Padre Garcia'),
    ('Paete', 'Paete'),
    ('Pagadian', 'Pagadian'),
    ('Pagalungan', 'Pagalungan'),
    ('Pagayawan (Tatarikan)', 'Pagayawan (Tatarikan)'),
    ('Pagbilao', 'Pagbilao'),
    ('Paglat', 'Paglat'),
    ('Pagsanghan', 'Pagsanghan'),
    ('Pagsanjan', 'Pagsanjan'),
    ('Pagudpud', 'Pagudpud'),
    ('Pakil', 'Pakil'),
    ('Palanan', 'Palanan'),
    ('Palanas', 'Palanas'),
    ('Palapag', 'Palapag'),
    ('Palauig', 'Palauig'),
    ('Palayan', 'Palayan'),
    ('Palimbang', 'Palimbang'),
    ('Palo', 'Palo'),
    ('Palompon', 'Palompon'),
    ('Paluan', 'Paluan'),
    ('Pambujan', 'Pambujan'),
    ('Pamplona', 'Pamplona'),
    ('Panabo', 'Panabo'),
    ('Panaon', 'Panaon'),
    ('Panay', 'Panay'),
    ('Pandag', 'Pandag'),
    ('Pandami', 'Pandami'),
    ('Pandan', 'Pandan'),
    ('Pandi', 'Pandi'),
    ('Panganiban (Payo)', 'Panganiban (Payo)'),
    ('Pangantucan', 'Pangantucan'),
    ('Pangil', 'Pangil'),
    ('Panglao', 'Panglao'),
    ('Panglima Estino (New Panamao)', 'Panglima Estino (New Panamao)'),
    ('Panglima Sugala (Balimbing)', 'Panglima Sugala (Balimbing)'),
    ('Pangutaran', 'Pangutaran'),
    ('Paniqui', 'Paniqui'),
    ('Panitan', 'Panitan'),
    ('Pantabangan', 'Pantabangan'),
    ('Pantao Ragat', 'Pantao Ragat'),
    ('Pantar', 'Pantar'),
    ('Pantukan', 'Pantukan'),
    ('Panukulan', 'Panukulan'),
    ('Paoay', 'Paoay'),
    ('Paombong', 'Paombong'),
    ('Paracale', 'Paracale'),
    ('Paracelis', 'Paracelis'),
    ('Parañaque', 'Parañaque'),
    ('Paranas (Wright)', 'Paranas (Wright)'),
    ('Parang', 'Parang'),
    ('Pasacao', 'Pasacao'),
    ('Pasay', 'Pasay'),
    ('Pasig', 'Pasig'),
    ('Pasil', 'Pasil'),
    ('Passi', 'Passi'),
    ('Pastrana', 'Pastrana'),
    ('Pasuquin', 'Pasuquin'),
    ('Pata', 'Pata'),
    ('Pateros', 'Pateros'),
    ('Patikul', 'Patikul'),
    ('Patnanungan', 'Patnanungan'),
    ('Patnongon', 'Patnongon'),
    ('Pavia', 'Pavia'),
    ('Payao', 'Payao'),
    ('Peñablanca', 'Peñablanca'),
    ('Peñaranda', 'Peñaranda'),
    ('Peñarrubia', 'Peñarrubia'),
    ('Perez', 'Perez'),
    ('Piagapo', 'Piagapo'),
    ('Piat', 'Piat'),
    ('Picong (Sultan Gumander)', 'Picong (Sultan Gumander)'),
    ('Piddig', 'Piddig'),
    ('Pidigan', 'Pidigan'),
    ('Pigcawayan', 'Pigcawayan'),
    ('Pikit', 'Pikit'),
    ('Pila', 'Pila'),
    ('Pilar', 'Pilar'),
    ('Pili', 'Pili'),
    ('Pililla', 'Pililla'),
    ('Pinabacdao', 'Pinabacdao'),
    ('Pinamalayan', 'Pinamalayan'),
    ('Pinamungajan', 'Pinamungajan'),
    ('Piñan (New Piñan)', 'Piñan (New Piñan)'),
    ('Pinili', 'Pinili'),
    ('Pintuyan', 'Pintuyan'),
    ('Pinukpuk', 'Pinukpuk'),
    ('Pio Duran', 'Pio Duran'),
    ('Pio V. Corpuz (Limbuhan)', 'Pio V. Corpuz (Limbuhan)'),
    ('Pitogo', 'Pitogo'),
    ('Placer', 'Placer'),
    ('Plaridel', 'Plaridel'),
    ('Pola', 'Pola'),
    ('Polanco', 'Polanco'),
    ('Polangui', 'Polangui'),
    ('Polillo', 'Polillo'),
    ('Polomolok', 'Polomolok'),
    ('Pontevedra', 'Pontevedra'),
    ('Poona Bayabao (Gata)', 'Poona Bayabao (Gata)'),
    ('Poona Piagapo', 'Poona Piagapo'),
    ('Porac', 'Porac'),
    ('Poro', 'Poro'),
    ('Pototan', 'Pototan'),
    ('Pozorrubio', 'Pozorrubio'),
    ('Presentacion (Parubcan)', 'Presentacion (Parubcan)'),
    ('President Carlos P. Garcia (Pitogo)', 'President Carlos P. Garcia (Pitogo)'),
    ('President Manuel A. Roxas', 'President Manuel A. Roxas'),
    ('President Quirino', 'President Quirino'),
    ('President Roxas', 'President Roxas'),
    ('Prieto Diaz', 'Prieto Diaz'),
    ('Prosperidad', 'Prosperidad'),
    ('Pualas', 'Pualas'),
    ('Pudtol', 'Pudtol'),
    ('Puerto Galera', 'Puerto Galera'),
    ('Puerto Princesa', 'Puerto Princesa'),
    ('Pugo', 'Pugo'),
    ('Pulilan', 'Pulilan'),
    ('Pulupandan', 'Pulupandan'),
    ('Pura', 'Pura'),
    ('Quezon', 'Quezon'),
    ('Quezon City', 'Quezon City'),
    ('Quinapondan', 'Quinapondan'),
    ('Quirino', 'Quirino'),
    ('Quirino (Angkaki)', 'Quirino (Angkaki)'),
    ('Ragay', 'Ragay'),
    ('Rajah Buayan', 'Rajah Buayan'),
    ('Ramon', 'Ramon'),
    ('Ramon Magsaysay (Liargo)', 'Ramon Magsaysay (Liargo)'),
    ('Ramos', 'Ramos'),
    ('Rapu-Rapu', 'Rapu-Rapu'),
    ('Real', 'Real'),
    ('Reina Mercedes', 'Reina Mercedes'),
    ('Remedios T. Romualdez', 'Remedios T. Romualdez'),
    ('Rizal', 'Rizal'),
    ('Rizal (Liwan)', 'Rizal (Liwan)'),
    ('Rizal (Marcos)', 'Rizal (Marcos)'),
    ('Rodriguez (Montalban)', 'Rodriguez (Montalban)'),
    ('Romblon', 'Romblon'),
    ('Ronda', 'Ronda'),
    ('Rosales', 'Rosales'),
    ('Rosario', 'Rosario'),
    ('Roseller Lim', 'Roseller Lim'),
    ('Roxas', 'Roxas'),
    ('Roxas City', 'Roxas City'),
    ('Sabangan', 'Sabangan'),
    ('Sablan', 'Sablan'),
    ('Sablayan', 'Sablayan'),
    ('Sabtang', 'Sabtang'),
    ('Sadanga', 'Sadanga'),
    ('Sagada', 'Sagada'),
    ('Sagay', 'Sagay'),
    ('Sagbayan (Borja)', 'Sagbayan (Borja)'),
    ('Sagñay', 'Sagñay'),
    ('Saguday', 'Saguday'),
    ('Saguiaran', 'Saguiaran'),
    ('Saint Bernard', 'Saint Bernard'),
    ('Salay', 'Salay'),
    ('Salcedo', 'Salcedo'),
    ('Salcedo (Baugen)', 'Salcedo (Baugen)'),
    ('Sallapadan', 'Sallapadan'),
    ('Salug', 'Salug'),
    ('Salvador', 'Salvador'),
    ('Salvador Benedicto', 'Salvador Benedicto'),
    ('Samal', 'Samal'),
    ('Samboan', 'Samboan'),
    ('Sampaloc', 'Sampaloc'),
    ('San Agustin', 'San Agustin'),
    ('San Andres', 'San Andres'),
    ('San Andres (Calolbon)', 'San Andres (Calolbon)'),
    ('San Antonio', 'San Antonio'),
    ('San Benito', 'San Benito'),
    ('San Carlos', 'San Carlos'),
    ('San Clemente', 'San Clemente'),
    ('San Dionisio', 'San Dionisio'),
    ('San Emilio', 'San Emilio'),
    ('San Enrique', 'San Enrique'),
    ('San Esteban', 'San Esteban'),
    ('San Fabian', 'San Fabian'),
    ('San Felipe', 'San Felipe'),
    ('San Fernando', 'San Fernando'),
    ('San Francisco', 'San Francisco'),
    ('San Francisco (Anao-Aon)', 'San Francisco (Anao-Aon)'),
    ('San Francisco (Aurora)', 'San Francisco (Aurora)'),
    ('San Gabriel', 'San Gabriel'),
    ('San Guillermo', 'San Guillermo'),
    ('San Ildefonso', 'San Ildefonso'),
    ('San Isidro', 'San Isidro'),
    ('San Jacinto', 'San Jacinto'),
    ('San Joaquin', 'San Joaquin'),
    ('San Jorge', 'San Jorge'),
    ('San Jose', 'San Jose'),
    ('San Jose de Buan', 'San Jose de Buan'),
    ('San Jose de Buenavista', 'San Jose de Buenavista'),
    ('San Jose del Monte', 'San Jose del Monte'),
    ('San Juan', 'San Juan'),
    ('San Juan (Cabalian)', 'San Juan (Cabalian)'),
    ('San Juan (Lapog)', 'San Juan (Lapog)'),
    ('San Julian', 'San Julian'),
    ('San Leonardo', 'San Leonardo'),
    ('San Lorenzo', 'San Lorenzo'),
    ('San Lorenzo Ruiz (Imelda)', 'San Lorenzo Ruiz (Imelda)'),
    ('San Luis', 'San Luis'),
    ('San Manuel', 'San Manuel'),
    ('San Manuel (Callang)', 'San Manuel (Callang)'),
    ('San Marcelino', 'San Marcelino'),
    ('San Mariano', 'San Mariano'),
    ('San Mateo', 'San Mateo'),
    ('San Miguel', 'San Miguel'),
    ('San Narciso', 'San Narciso'),
    ('San Nicolas', 'San Nicolas'),
    ('San Pablo', 'San Pablo'),
    ('San Pascual', 'San Pascual'),
    ('San Pedro', 'San Pedro'),
    ('San Policarpo', 'San Policarpo'),
    ('San Quintin', 'San Quintin'),
    ('San Rafael', 'San Rafael'),
    ('San Remigio', 'San Remigio'),
    ('San Ricardo', 'San Ricardo'),
    ('San Roque', 'San Roque'),
    ('San Sebastian', 'San Sebastian'),
    ('San Simon', 'San Simon'),
    ('San Teodoro', 'San Teodoro'),
    ('San Vicente', 'San Vicente'),
    ('Sanchez-Mira', 'Sanchez-Mira'),
    ('Santa', 'Santa'),
    ('Santa Ana', 'Santa Ana'),
    ('Santa Barbara', 'Santa Barbara'),
    ('Santa Catalina', 'Santa Catalina'),
    ('Santa Cruz', 'Santa Cruz'),
    ('Santa Elena', 'Santa Elena'),
    ('Santa Fe', 'Santa Fe'),
    ('Santa Fe (Imugan)', 'Santa Fe (Imugan)'),
    ('Santa Ignacia', 'Santa Ignacia'),
    ('Santa Josefa', 'Santa Josefa'),
    ('Santa Lucia', 'Santa Lucia'),
    ('Santa Magdalena', 'Santa Magdalena'),
    ('Santa Marcela', 'Santa Marcela'),
    ('Santa Margarita', 'Santa Margarita'),
    ('Santa Maria', 'Santa Maria'),
    ('Santa Maria (Imelda)', 'Santa Maria (Imelda)'),
    ('Santa Monica (Sapao)', 'Santa Monica (Sapao)'),
    ('Santa Praxedes', 'Santa Praxedes'),
    ('Santa Rita', 'Santa Rita'),
    ('Santa Rosa', 'Santa Rosa'),
    ('Santa Teresita', 'Santa Teresita'),
    ('Santander', 'Santander'),
    ('Santiago', 'Santiago'),
    ('Santo Domingo', 'Santo Domingo'),
    ('Santo Niño', 'Santo Niño'),
    ('Santo Niño (Faire)', 'Santo Niño (Faire)'),
    ('Santo Tomas', 'Santo Tomas'),
    ('Santol', 'Santol'),
    ('Sapa-Sapa', 'Sapa-Sapa'),
    ('Sapad', 'Sapad'),
    ('Sapang Dalaga', 'Sapang Dalaga'),
    ('Sapian', 'Sapian'),
    ('Sara', 'Sara'),
    ('Sarangani', 'Sarangani'),
    ('Sariaya', 'Sariaya'),
    ('Sarrat', 'Sarrat'),
    ('Sasmuan', 'Sasmuan'),
    ('Sebaste', 'Sebaste'),
    ('Senator Ninoy Aquino', 'Senator Ninoy Aquino'),
    ('Sergio Osmeña Sr.', 'Sergio Osmeña Sr.'),
    ('Sevilla', 'Sevilla'),
    ('Shariff Aguak (Maganoy)', 'Shariff Aguak (Maganoy)'),
    ('Shariff Saydona Mustapha', 'Shariff Saydona Mustapha'),
    ('Siasi', 'Siasi'),
    ('Siaton', 'Siaton'),
    ('Siay', 'Siay'),
    ('Siayan', 'Siayan'),
    ('Sibagat', 'Sibagat'),
    ('Sibalom', 'Sibalom'),
    ('Sibonga', 'Sibonga'),
    ('Sibuco', 'Sibuco'),
    ('Sibulan', 'Sibulan'),
    ('Sibunag', 'Sibunag'),
    ('Sibutad', 'Sibutad'),
    ('Sibutu', 'Sibutu'),
    ('Sierra Bullones', 'Sierra Bullones'),
    ('Sigay', 'Sigay'),
    ('Sigma', 'Sigma'),
    ('Sikatuna', 'Sikatuna'),
    ('Silago', 'Silago'),
    ('Silang', 'Silang'),
    ('Silay', 'Silay'),
    ('Silvino Lobos', 'Silvino Lobos'),
    ('Simunul', 'Simunul'),
    ('Sinacaban', 'Sinacaban'),
    ('Sinait', 'Sinait'),
    ('Sindangan', 'Sindangan'),
    ('Siniloan', 'Siniloan'),
    ('Siocon', 'Siocon'),
    ('Sipalay', 'Sipalay'),
    ('Sipocot', 'Sipocot'),
    ('Siquijor', 'Siquijor'),
    ('Sirawai', 'Sirawai'),
    ('Siruma', 'Siruma'),
    ('Sison', 'Sison'),
    ('Sitangkai', 'Sitangkai'),
    ('Socorro', 'Socorro'),
    ('Sofronio Española', 'Sofronio Española'),
    ('Sogod', 'Sogod'),
    ('Solana', 'Solana'),
    ('Solano', 'Solano'),
    ('Solsona', 'Solsona'),
    ('Sominot (Don Mariano Marcos)', 'Sominot (Don Mariano Marcos)'),
    ('Sorsogon City', 'Sorsogon City'),
    ('South Ubian', 'South Ubian'),
    ('South Upi', 'South Upi'),
    ('Sual', 'Sual'),
    ('Subic', 'Subic'),
    ('Sudipen', 'Sudipen'),
    ('Sugbongcogon', 'Sugbongcogon'),
    ('Sugpon', 'Sugpon'),
    ('Sulat', 'Sulat'),
    ('Sulop', 'Sulop'),
    ('Sultan Dumalondong', 'Sultan Dumalondong'),
    ('Sultan Kudarat (Nuling)', 'Sultan Kudarat (Nuling)'),
    ('Sultan Mastura', 'Sultan Mastura'),
    ('Sultan Naga Dimaporo (Karomatan)', 'Sultan Naga Dimaporo (Karomatan)'),
    ('Sultan sa Barongis (Lambayong)', 'Sultan sa Barongis (Lambayong)'),
    ('Sultan Sumagka (Talitay)', 'Sultan Sumagka (Talitay)'),
    ('Sumilao', 'Sumilao'),
    ('Sumisip', 'Sumisip'),
    ('Surallah', 'Surallah'),
    ('Surigao City', 'Surigao City'),
    ('Suyo', 'Suyo'),
    ('T'Boli', 'T'Boli'),
    ('Taal', 'Taal'),
    ('Tabaco', 'Tabaco'),
    ('Tabango', 'Tabango'),
    ('Tabina', 'Tabina'),
    ('Tabogon', 'Tabogon'),
    ('Tabontabon', 'Tabontabon'),
    ('Tabuan-Lasa', 'Tabuan-Lasa'),
    ('Tabuelan', 'Tabuelan'),
    ('Tabuk', 'Tabuk'),
    ('Tacloban', 'Tacloban'),
    ('Tacurong', 'Tacurong'),
    ('Tadian', 'Tadian'),
    ('Taft', 'Taft'),
    ('Tagana-an', 'Tagana-an'),
    ('Tagapul-an', 'Tagapul-an'),
    ('Tagaytay', 'Tagaytay'),
    ('Tagbilaran', 'Tagbilaran'),
    ('Tagbina', 'Tagbina'),
    ('Tagkawayan', 'Tagkawayan'),
    ('Tago', 'Tago'),
    ('Tagoloan', 'Tagoloan'),
    ('Tagoloan II', 'Tagoloan II'),
    ('Tagudin', 'Tagudin'),
    ('Taguig', 'Taguig'),
    ('Tagum', 'Tagum'),
    ('Talacogon', 'Talacogon'),
    ('Talaingod', 'Talaingod'),
    ('Talakag', 'Talakag'),
    ('Talalora', 'Talalora'),
    ('Talavera', 'Talavera'),
    ('Talayan', 'Talayan'),
    ('Talibon', 'Talibon'),
    ('Talipao', 'Talipao'),
    ('Talisay', 'Talisay'),
    ('Talisayan', 'Talisayan'),
    ('Talugtug', 'Talugtug'),
    ('Talusan', 'Talusan'),
    ('Tambulig', 'Tambulig'),
    ('Tampakan', 'Tampakan'),
    ('Tamparan', 'Tamparan'),
    ('Tampilisan', 'Tampilisan'),
    ('Tanauan', 'Tanauan'),
    ('Tanay', 'Tanay'),
    ('Tandag', 'Tandag'),
    ('Tandubas', 'Tandubas'),
    ('Tangalan', 'Tangalan'),
    ('Tangcal', 'Tangcal'),
    ('Tangub', 'Tangub'),
    ('Tanjay', 'Tanjay'),
    ('Tantangan', 'Tantangan'),
    ('Tanudan', 'Tanudan'),
    ('Tanza', 'Tanza'),
    ('Tapaz', 'Tapaz'),
    ('Tapul', 'Tapul'),
    ('Taraka', 'Taraka'),
    ('Tarangnan', 'Tarangnan'),
    ('Tarlac City', 'Tarlac City'),
    ('Tarragona', 'Tarragona'),
    ('Tayabas', 'Tayabas'),
    ('Tayasan', 'Tayasan'),
    ('Taysan', 'Taysan'),
    ('Taytay', 'Taytay'),
    ('Tayug', 'Tayug'),
    ('Tayum', 'Tayum'),
    ('Teresa', 'Teresa'),
    ('Ternate', 'Ternate'),
    ('Tiaong', 'Tiaong'),
    ('Tibiao', 'Tibiao'),
    ('Tigaon', 'Tigaon'),
    ('Tigbao', 'Tigbao'),
    ('Tigbauan', 'Tigbauan'),
    ('Tinambac', 'Tinambac'),
    ('Tineg', 'Tineg'),
    ('Tinglayan', 'Tinglayan'),
    ('Tingloy', 'Tingloy'),
    ('Tinoc', 'Tinoc'),
    ('Tipo-Tipo', 'Tipo-Tipo'),
    ('Titay', 'Titay'),
    ('Tiwi', 'Tiwi'),
    ('Tobias Fornier (Dao)', 'Tobias Fornier (Dao)'),
    ('Toboso', 'Toboso'),
    ('Toledo', 'Toledo'),
    ('Tolosa', 'Tolosa'),
    ('Tomas Oppus', 'Tomas Oppus'),
    ('Torrijos', 'Torrijos'),
    ('Trece Martires', 'Trece Martires'),
    ('Trento', 'Trento'),
    ('Trinidad', 'Trinidad'),
    ('Tuao', 'Tuao'),
    ('Tuba', 'Tuba'),
    ('Tubajon', 'Tubajon'),
    ('Tubao', 'Tubao'),
    ('Tubaran', 'Tubaran'),
    ('Tubay', 'Tubay'),
    ('Tubigon', 'Tubigon'),
    ('Tublay', 'Tublay'),
    ('Tubo', 'Tubo'),
    ('Tubod', 'Tubod'),
    ('Tubungan', 'Tubungan'),
    ('Tuburan', 'Tuburan'),
    ('Tudela', 'Tudela'),
    ('Tugaya', 'Tugaya'),
    ('Tuguegarao', 'Tuguegarao'),
    ('Tukuran', 'Tukuran'),
    ('Tulunan', 'Tulunan'),
    ('Tumauini', 'Tumauini'),
    ('Tunga', 'Tunga'),
    ('Tungawan', 'Tungawan'),
    ('Tupi', 'Tupi'),
    ('Turtle Islands (Taganak)', 'Turtle Islands (Taganak)'),
    ('Tuy', 'Tuy'),
    ('Ubay', 'Ubay'),
    ('Umingan', 'Umingan'),
    ('Ungkaya Pukan', 'Ungkaya Pukan'),
    ('Unisan', 'Unisan'),
    ('Upi', 'Upi'),
    ('Urbiztondo', 'Urbiztondo'),
    ('Urdaneta', 'Urdaneta'),
    ('Uson', 'Uson'),
    ('Uyugan', 'Uyugan'),
    ('Valderrama', 'Valderrama'),
    ('Valencia', 'Valencia'),
    ('Valencia (Luzurriaga)', 'Valencia (Luzurriaga)'),
    ('Valenzuela', 'Valenzuela'),
    ('Valladolid', 'Valladolid'),
    ('Vallehermoso', 'Vallehermoso'),
    ('Veruela', 'Veruela'),
    ('Victoria', 'Victoria'),
    ('Victorias', 'Victorias'),
    ('Viga', 'Viga'),
    ('Vigan', 'Vigan'),
    ('Villaba', 'Villaba'),
    ('Villanueva', 'Villanueva'),
    ('Villareal', 'Villareal'),
    ('Villasis', 'Villasis'),
    ('Villaverde (Ibung)', 'Villaverde (Ibung)'),
    ('Villaviciosa', 'Villaviciosa'),
    ('Vincenzo A. Sagun', 'Vincenzo A. Sagun'),
    ('Vintar', 'Vintar'),
    ('Vinzons', 'Vinzons'),
    ('Virac', 'Virac'),
    ('Wao', 'Wao'),
    ('Zamboanga City', 'Zamboanga City'),
    ('Zamboanguita', 'Zamboanguita'),
    ('Zaragoza', 'Zaragoza'),
    ('Zarraga', 'Zarraga'),
    ('Zumarraga', 'Zumarraga'),
)
